name: Build and Package (JavaFX)

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  build:
    name: Build on ${{ matrix.os.name }}
    runs-on: ${{ matrix.os.runner }}
    strategy:
      fail-fast: false
      matrix:
        os:
          - { runner: 'macos-14',   name: 'macOS (arm64)', profile: 'mac-aarch64', artifact_suffix: 'macos-arm64' }
          - { runner: 'macos-13',   name: 'macOS (x64)',   profile: 'mac-x64',     artifact_suffix: 'macos-x64' }
          - { runner: 'ubuntu-latest', name: 'Linux',      profile: 'linux',       artifact_suffix: 'linux' }
          - { runner: 'windows-latest', name: 'Windows',   profile: 'windows',     artifact_suffix: 'windows' }

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Temurin JDK 25
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '25'
          cache: 'maven'

      - name: Show Java and OS info
        run: |
          java -version
          mvn -v
        shell: bash

      - name: Build with Maven (profile ${{ matrix.os.profile }})
        run: mvn -B -DskipTests -P${{ matrix.os.profile }} clean package
        shell: bash

      - name: Upload native package artifact
        uses: actions/upload-artifact@v4
        with:
          name: family-tree-editor-${{ matrix.os.artifact_suffix }}
          path: |
            target/dist/*
          if-no-files-found: warn
